// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface CourseStoryblok {
  image?: AssetStoryblok;
  title?: string;
  description?: string;
  category: string;
  fulltime?: boolean;
  parttime?: boolean;
  type: string;
  component: "course";
  _uid: string;
  [k: string]: any;
}

export interface CoursesStoryblok {
  courses?: (CourseStoryblok | CoursesStoryblok | PageStoryblok)[];
  component: "courses";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (CourseStoryblok | CoursesStoryblok | PageStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}
