// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.

export interface RichtextStoryblok {
  type: string
  content?: RichtextStoryblok[]
  marks?: RichtextStoryblok[]
  attrs?: any
  text?: string
  [k: string]: any
}

export interface AboutPageStoryblok {
  header?: string
  subtitle?: string
  body?: RichtextStoryblok
  component: "about page"
  _uid: string
  [k: string]: any
}

export interface AssetStoryblok {
  alt?: string
  copyright?: string
  id: number
  filename: string
  name: string
  title?: string
  focus?: string
  [k: string]: any
}

export interface TableStoryblok {
  thead: {
    _uid: string
    value?: string
    component: number
    [k: string]: any
  }[]
  tbody: {
    _uid: string
    body: {
      _uid?: string
      value?: string
      component?: number
      [k: string]: any
    }[]
    component: number
    [k: string]: any
  }[]
  [k: string]: any
}

export interface CourseStoryblok {
  image?: AssetStoryblok
  title?: string
  description?: string
  category: string
  fulltime?: boolean
  parttime?: boolean
  type: string
  location?: string
  overview: RichtextStoryblok
  fees?: RichtextStoryblok
  primaryButtonText?: string
  downloadBrochureButtonText?: string
  downloadBrochureUrl?: string
  timetable?: TableStoryblok
  component: "course"
  _uid: string
  [k: string]: any
}

export interface CoursePageStoryblok {
  tabs?: ("" | "OVERVIEW" | "TIMETABLE" | "FEES" | "FAQS" | "CONTACT")[]
  component: "course page"
  _uid: string
  [k: string]: any
}

export interface FaqStoryblok {
  title?: string
  description?: RichtextStoryblok
  component: "faq"
  _uid: string
  [k: string]: any
}

export interface HomePageStoryblok {
  heroSectionHeaderText?: string
  heroSectionSubtitleText?: string
  heroSectionPrimaryButtonText?: string
  heroSectionSecondaryButtonText?: string
  courseSectionHeader?: string
  courseSectionSubtitle?: string
  courseSectionCategories?: (
    | ""
    | "ALL"
    | "ACTING-VOICE-COMMUNICATION"
    | "DESIGN-FASHION-MAKEUP"
    | "GAMES-FILM-PHOTOGRAPHY"
    | 'MARKETING-MANAGEMENT"'
    | "MUSIC-SOUND-PRODUCTION"
  )[]
  component: "home page"
  _uid: string
  [k: string]: any
}

export interface NavbarStoryblok {
  primaryButtonText?: string
  component: "navbar"
  _uid: string
  [k: string]: any
}

export interface PageStoryblok {
  body?: (
    | AboutPageStoryblok
    | CourseStoryblok
    | CoursePageStoryblok
    | FaqStoryblok
    | HomePageStoryblok
    | NavbarStoryblok
    | PageStoryblok
  )[]
  component: "page"
  _uid: string
  [k: string]: any
}
