import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Footer } from "@/app/components/footer";
import { Header } from "@/app/components/header";

const inter = Inter({ subsets: ["latin"] });

const Main = ({ children }: { children: ReactNode }) => {
  return <main>{children}</main>;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: { lang: "en" | "nl" };
    contact: ReactNode;
  }>
) {
  const { children, params, contact } = props;

  return (
    <html
      lang={params.lang}
      className={`${inter.className} bg-black text-primary`}
    >
      <body>
        <Header lang={params.lang} />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
