import type { ReactNode } from "react";
import type { Metadata } from "next";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";

import { env } from "@/env";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: env.NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN,
  use: [apiPlugin],
});

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: { lang: "en" | "nl" };
    contact: ReactNode;
  }>
) {
  const { children, contact } = props;

  return (
    <>
      {children} {contact}
    </>
  );
}
