import type { ReactNode } from "react";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: { lang: "en" | "nl" };
    contact: ReactNode;
  }>
) {
  const { children, contact } = props;
  console.log(contact);

  return (
    <>
      {children} {contact}
    </>
  );
}
